image: archlinux:base-devel-20210221.0.15908

stages:
    - compile

before_script:
    - pacman -Sy
    - pacman -S --noconfirm glibc git jdk-openjdk
    - ./gradlew init

compile:
    stage: compile
    script:
        - ./gradlew clean
        - ./gradlew compileJava
