# Gaia Sky configuration file

# Configuration version number
configVersion: 30301

#
# Data configuration
#
data:
  # Location of the data folder.
  # Windows and macOS: in your user directory: $HOME/.gaiasky/data
  # Linux: ~/.local/share/gaiasky/data
  location: null
  # Data files to load at startup, using the relative form from the data location (placeholder is '$data/').
  # They should use the format '$/data/[dataset-name]/dataset.json.
  # The base data pack '$data/default-data/dataset.json' should always be there.
  dataFiles:
    - $data/default-data/dataset.json
  # Location of the skybox used for cubemap reflections within the data folder (data/tex/skybox/[...]/)
  reflectionSkyboxLocation: $data/default-data/tex/skybox/gaiasky/
  # Use all terms in position algorithms (VSOP87 and moon coordinates)
  highAccuracy: false
  # Use real attitude or NSL for Gaia
  realGaiaAttitude: false

#
# Performance configuration
#
performance:
  # Is multithreading enabled?
  multithreading: true
  # Number of worker threads to use for background
  # metadata updates. Set to 0 to default to the number
  # of logical processors.
  numberThreads: 0

#
# Graphics configuration
#
graphics:
  # Graphics quality setting in [LOW|NORMAL|HIGH|ULTRA]
  quality: NORMAL
  # Resolution in windowed mode, use 0 for default
  resolution: [0, 0]
  # Make the window resizable, in windowed mode
  resizable: true
  # Full screen configuration
  fullScreen:
    # Is fullscreen active?
    active: false
    # Resolution in full screen mode
    resolution: [1920, 1080]
  # Enable VSYNC
  vsync: true
  # Limit frame rate, set to 0 to disable frame limiter
  fpsLimit: 0.0
  # Here be dragons! This is just for testing. Unstable!
  # Back buffer scaling factor - just leave it at 1
  backBufferScale: 1.0
  # Here be dragons! This is just for testing. Unstable!
  # Enable dynamic resolution  - kicks in during low FPS by reducing the backbuffer size
  dynamicResolution: false
  # This activates output to the default monitor. Deactivate only to enable headless mode.
  screenOutput: true

#
# Scene configuration
#
scene:
  # Name of the home object
  homeObject: Earth
  # Object fade time in ms
  fadeMs: 1500
  # Camera configuration
  camera:
    # Camera speed limit
    # 0 - 100 km/h
    # 1 - 0.5c
    # 2 - 0.8c
    # 3 - 0.9c
    # 4 - 0.99c
    # 5 - 0.99999c
    # 6 - c (3e8 m/s)
    # 7 - 2*c
    # 8 - 10*c
    # 9 - 1000*c
    # 10 - 1 AU/s
    # 11 - 10 AU/s
    # 12 - 1000 AU/s
    # 13 - 10000 AU/s
    # 14 - 1 pc/s
    # 15 - 2 pc/s
    # 16 - 10 pc/s
    # 17 - 1000 pc/s
    # 18 - No limit
    speedLimitIndex: 18
    # Camera speed multiplier.
    speed: 10.0
    # Camera turn velocity.
    turn: 3000.0
    # Camera rotation.
    rotate: 5000.0
    # Field of view in degrees.
    fov: 45.0
    # Cinematic camera
    cinematic: false
    # Target on in free mode. This scales the velocity of the camera according
    # to the distance to the closest object.
    targetMode: true
    # Focus lock configuration, when camera is in focus mode.
    focusLock:
      # Lock camera position to focus position.
      position: true
      # Lock camera position to focus orientation.
      orientation: false
  # Star settings.
  star:
    # Star brightness factor.
    brightness: 2.0
    # Modulate the brightness of stars with this power.
    power: 0.75
    # Size scaling of stars.
    pointSize: 8.2
    # Control the glow amount when close to stars.
    # Should be set rather low, i.e., in [0.01, 0.5].
    glowFactor: 0.06
    # Texture index, see $GS_DATA/tex/base/star-tex-xx-low.png
    # 1 - horizontal spike
    # 2 - god rays
    # 3 - horizontal and vertical spikes
    # 4 - simple radial profile
    textureIndex: 4
    # Star opacity mapping, as in [min, max]
    opacity: [0.0, 1.0]
    # Star groups
    group:
      # Enable or disable the star billboards when stars are close
      billboard: true
      # Maximum number of star billboards per group
      numBillboard: 30
      # Maximum number of labels per star group
      numLabel: 50
      # Maximum number of velocity vectors per star group
      numVelocityVector: 500
    # Star threshold values
    threshold:
      # Threshold radius/distance for stars. This controls the threshold to render stars as points or as quads
      # radius/distance limit for rendering as quad. If angle is any bigger, we render as a model.
      quad: 0.0
      # radius/distance limit for rendering as point. If angle is any bigger, we render as quad.
      point: 1.7e-8
      # radius/distance limit for rendering at all. If angle is smaller than this quantity, no rendering happens.
      none: 0.0
  # Label settings
  label:
    # Label size factor
    size: 0.85
    # Controls the number of labels to render
    number: 1.3
  # Line width factor
  lineWidth: 1.0
  # Proper motion arrow settings
  properMotion:
    # Length factor of proper motion vectors [500.0 - 50000.0]
    length: 25000.0
    # Scale factor of proper motion vectors [1.0 - 10.0]
    number: 5.0
    # Color mode for velocity vectors
    # 0 - direction
    # 1 - length (speed)
    # 2 - has radial velocity
    # 3 - redshift
    # 4 - single color
    colorMode: 0
    # Whether to show arrowheads or not
    arrowHeads: true
  # Octree settings
  octree:
    # In the case of multifile LOD datasets (such as DR2+), this setting contains
    # the maximum number of stars loaded at a time. If the number of loaded stars
    # exceeds this setting, the system will start looking for the best candidates
    # to be unloaded and start unloading data. Should not be set too low, and this should
    # be balanced with the dataset and the draw distance.
    # 6.0 M is calibrated to use 6 GB heap space with the default dataset
    maxStars: 7000000
    # The octant thresholds:
    # - radius/distance above which we start painting stars in octant with fade in. Angle in radians.
    # - radius/distance below which we paint stars in octant with fade out. Above this angle, inner stars are painted with full brightness. Angle in radians.
    threshold: [1.4, 1.8]
    # If on, particles fade in and out between levels of detail
    fade: true
  # Renderer settings
  renderer:
    # Point cloud mode, one of [TRIANGLES|TRIANGLES_INSTANCED|POINTS]
    # TRIANGLES is the new mode. Triangles are sent to the GPU in VBOs with VAOs. Faster on newer hardware and geometrically correct.
    # TRIANGLES_INSTANCED is a variation of TRIANGLES. Saves x4 graphics memory. Your mileage may vary with this one.
    # POINTS is the legacy mode. It is faster on old hardware but geometrically incorrect, especially in 360 and planetarium modes
    pointCloud: POINTS
    # Line renderer mode, one of [GL_LINES|POLYLINE_QUADSTRIP]
    line: POLYLINE_QUADSTRIP
    # Orbit renderer, one of [LINE_MODE_SETTING|GPU_VBO]
    orbit: LINE_MODE_SETTING
    # Ambient light value
    ambient: 0.0
    # Shadow settings
    shadow:
      # Enable shadows
      active: true
      # Shadow map resolution
      resolution: 1024
      # Maximum number of shadows
      number: 4
    # Elevation representation settings
    elevation:
      # Elevation type [TESSELLATION|PARALLAX_MAPPING|NONE]
      type: TESSELLATION
      # Elevation multiplier, in [0.0, 10.0]
      multiplier: 2.5
      # Tessellation quality, in [1.0, 7.0]
      quality: 4.0
  # Crosshair settings
  crosshair:
    # Show crosshair on focus object
    focus: true
    # Show crosshair on closest object
    closest: true
    # Show crosshair on home object
    home: false
  # Initialization configuration
  initialization:
    # Lazy initialization of textures
    lazyTexture: true
    # Lazy initialization of meshes
    lazyMesh: true
  # Visibility of components
  visibility:
    Stars: true
    Planets: true
    Moons: true
    Satellites: true
    Asteroids: false
    Clusters: false
    MilkyWay: true
    Galaxies: true
    Nebulae: true
    Meshes: false
    Equatorial: false
    Ecliptic: false
    Galactic: false
    RecursiveGrid: false
    Labels: true
    Orbits: true
    Locations: false
    CosmicLocations: true
    Countries: false
    Constellations: false
    Boundaries: false
    Ruler: true
    Effects: false
    Atmospheres: true
    Clouds: true
    Axes: true
    VelocityVectors: false
    Titles: false
    Others: true

#
# Program configuration
#
program:
  # The default time zone to use. One of [UTC|SYSTEM_DEFAULT]
  timeZone: UTC
  # Enable safe mode, which disables advanced graphics features.
  # For instance, it disables float buffers and creates no velocity buffer (no motion blur)
  safeMode: false
  # Print debug information to the terminal
  debugInfo: false
  # Offline mode: never attempt any connection - disables updates and dataset downloads
  offlineMode: false
  # Save all procedurally-generated textures to the data folder
  # WARN: watch your disk space!
  saveProceduralTextures: false
  # Minimap settings
  minimap:
    # Display the minimap
    active: false
    # Minimap side size in [150,350]
    size: 200.0
    # Put minimap in a window
    inWindow: false
  # File chooser dialog configuration
  fileChooser:
    # Last location
    lastLocation: null
    # Show hidden files
    showHidden: false
  # Pointer configuration
  pointer:
    # Display the coordinates of the pointer projected on the sides of the window
    coordinates: true
    # Pointer guides configuration
    guides:
      # Display pointer guides
      active: false
      # Color of pointer guides in RGBA
      color: [1.0, 1.0, 1.0, 0.3]
      # Width of pointer guide lines
      width: 1.5
  # Recursive grid configuration
  recursiveGrid:
    # Origin of the recursive grid in [FOCUS|REFSYS]
    origin: REFSYS
    # If origin is refsys, this option adds projection lines to the current focus
    projectionLines: true
  # Stereoscopic mode (3D)
  modeStereo:
    # Start in 3D mode
    active: false
    # The stereoscopic profile, one of [VR_HEADSET|HORIZONTAL_3DTV|VERTICAL_3DTV|CROSSEYE|PARALLEL_VIEW|ANAGLYPH]
    profile: CROSSEYE
  # Cubemap mode
  modeCubemap:
    # Start in cubemap mode
    active: false
    # Projection to use for the cubemap mode, in [EQUIRECTANGULAR|CYLINDRICAL|HAMMER|AZIMUTHAL_EQUIDISTANT]
    # Set to 'fisheye' for planetarium mode
    projection: EQUIRECTANGULAR
    # The resolution at which to render each side of the cubemap
    faceResolution: 1500
    # Planetarium mode configuration
    planetarium:
      # Aperture angle, in degrees
      aperture: 180.0
      # Devaition angle of the focus mode from the zenith, in degrees
      angle: 50.0
  # Gaia Sky instance connection (master-slave)
  net:
    # Enable the REST API on this TCP port (negative to disable)
    restPort: -1
    # Master configuration
    master:
      # Is master instance
      # This means that the status is sent over the network to the slaves
      # Incompatible with slave>is
      active: false
      # List of URLs of the slave instances
      # Example: [http://localhost:13900/api/, http://localhost:13901/api]
      slaves: []
    # Slave configuration
    slave:
      # In a client-server configuration, this makes this instance act as a slave
      # which receives input events over the network
      # Incompatible with master>is
      active: false
      # Location of the .mpcdi configuration file for this instance
      # Only needed if program.net.slave is true
      configFile: null
      # Warp pfm file
      warpFile: null
      # Blend png file
      blendFile: null
      # Yaw angle (turn head right)
      yaw: 0.0
      # Pitch angle (turn head up)
      pitch: 0.0
      # Roll angle (rotate head cw)
      roll: 0.0
  # Default location of script files, leave empty for default
  scriptsLocation: null
  # User interface configuration
  ui:
    # The UI theme, in [dark-green|dark-blue|dark-orange|night-red]
    theme: dark-green
    # The UI scale factor
    scale: 1.0
    # Preferred distance units [PC|LY]
    distanceUnits: PC
    # Show mode change pop-up dialogs (panorama, planetarium, stereoscopic, and game modes)
    modeChangeInfo: true
  # Ask for confirmation on exit
  exitConfirmation: true
  # Set to 'default' to use the system default locale, set to
  # language tag (see java.util.Locale#forLanguageTag(), java 7+) to change
  # the locale (en_GB, en_US, es_ES, de_DE, fr, etc.)
  # Leave null to use default locale
  locale: null
  # Update configuration
  update:
    # Last update check date
    lastCheck: null
    # Server version of the last check
    lastVersion: null
  # Pointers to some resources
  url:
    # URL to check for new versions
    versionCheck: https://codeberg.org/api/v1/repos/gaiasky/gaiasky/tags
    # Data repository location
    dataMirror: https://gaia.ari.uni-heidelberg.de/gaiasky/files/repository/
    # Data descriptor file location
    # This can also point to a local repository description file (use file://)
    dataDescriptor: https://gaia.ari.uni-heidelberg.de/gaiasky/files/repository/gaiasky-data-030301.json.gz

#
# Controls configuration
#
controls:
  # Gamepad configuration
  gamepad:
    # Controller mappings file
    mappingsFile: mappings/SDL_Controller.controller
    # Invert look X axis
    invertX: false
    # Invert look Y axis
    invertY: true
    # Blacklist of controller names. All controllers here will not be
    # processed by Gaia Sky. Find the connected controller names in the Preferences
    # window, Controls tab.
    # Example: blacklist: [Microsoft Xbox 360 pad, Playstation 4 dualshock]
    blacklist: []

#
# Frame output configuration
#
frame:
  # Output directory of still frames
  location: null
  # Either JPG or PNG
  format: JPG
  # Quality of jpg, in [0,1]
  quality: 0.93
  # The frame mode: [SIMPLE|REDRAW]
  # simple - the current openGL buffer is written to a file. Screenshot will look exactly like the screen
  # redraw - the image is redrawn with optionally different effects and resolution, and then it is written to a file.
  mode: SIMPLE
  # Still frame image resolution, only in redraw mode
  resolution: [1280,720]
  # File name prefix for still frames
  prefix: gaiasky
  # Stamp frames with current simulation time
  time: false
  # The target frame rate of the render system
  targetFps: 60

#
# Screenshots configuration
#
screenshot:
  # Output directory of screenshots
  location:
  # Either JPG or PNG
  format: JPG
  # Quality of jpg, in [0,1]
  quality: 0.93
  # The screenshot mode: [SIMPLE|REDRAW]
  # simple - the current openGL buffer is written to a file. Screenshot will look exactly like the screen
  # redraw - the image is redrawn with optionally different effects and resolution, and then it is written to a file.
  mode: SIMPLE
  # Screenshot image resolution, only in redraw mode
  resolution: [1280,720]

#
# Camrecorder configuration
#
camrecorder:
  # Target frame rate of the camrecorder system
  targetFps: 60
  # Keyframe configuration
  keyframe:
    # Interpolation method for the camera position, in [SPLINE|LINEAR]
    position: SPLINE
    # Interpolation method for the camera orientation, in [SPLINE|LINEAR]
    orientation: SPLINE
  # Automatically activate frame output system when playing a camera path
  auto: false

#
# Post-processing configuration
#
postprocess:
  # Antialiasing mode, one of [NONE|FXAA|NFAA]
  antialias: FXAA
  # Bloom settings
  bloom:
    # Intensity of bloom
    intensity: 0.0
    # Frame buffer scale
    fboScale: 0.5
  # Unsharp mask effect
  unsharpMask:
    # Sharpen factor, in [0,3]
    factor: 0.0
  # Motion blur effect
  motionBlur:
    active: false
  # Screen space reflections
  ssr:
    active: false
  # Lens flare effect settings
  lensFlare:
    active: true
    intensity: 0.15
    numGhosts: 8
    haloWidth: 0.5
    blurPasses: 35
    flareSaturation: 0.8
    bias: -0.98
    texLensColor: $data/default-data/tex/base/lenscolor.png
    texLensDirt: $data/default-data/tex/base/lensdirt%#QUAL#%.jpg
    texLensStarburst: $data/default-data/tex/base/lensstarburst.jpg
    fboScale: 0.2
  # Light glow effect
  lightGlow:
    active: true
    samples: 10
  # Re-projection as post-processing.
  # Modes are:
  # DISABLED
  # DEFAULT, ACCURATE
  # STEREOGRAPHIC_SCREEN, STEREOGRAPHIC_LONG, STEREOGRAPHIC_SHORT, STEREOGRAPHIC_180
  # LAMBERT_SCREEN, LAMBERT_LONG, LAMBERT_SHORT, LAMBERT_180
  # ORTHOGRAPHIC_SCREEN, ORTHOGRAPHIC_LONG, ORTHOGRAPHIC_SHORT, ORTHOGRAPHIC_180
  reprojection:
    active: false
    mode: DISABLED
  # Image levels
  levels:
    # Brightness level in [-1,1] (default=0)
    brightness: 0.0
    # Contrast level in [0,2] (default=1)
    contrast: 1.0
    # Hue level in [0,1] (default=1)
    hue: 1.0
    # Saturation level in [0,2] (default=1)
    saturation: 1.0
    # Gamma correction value in [0,3] (default=1)
    gamma: 1.0
  # Tone mapping algorithms
  toneMapping:
    # Algorithm to use, one of [AUTO|EXPOSURE|ACES|UNCHARTED|FILMIC|NONE]
    type: NONE
    # When type=exposure, set the exposure here, in [0,n]
    exposure: 0.0

#
# Spacecraft configuration
#
spacecraft:
  # Velocity vector always aligned with spacecraft direction vector
  velocityDirection: false
  # Whether to show the direction and up axes of the spacecraft
  showAxes: false

#
# Proxy configuration
#

#proxy:
#   useSystemProxies: true
#   http:
#     port: 8080
#     host: 127.0.0.1
#     username: myself
#     password: secret
#     nonProxyHosts: localhost,192.168.0.*
#   https:
#     port: 8080
#     host: 127.0.0.1
#     username: myself
#     password: secret
#     nonProxyHosts: localhost,192.168.0.*
#   ftp:
#     port: 8080
#     host: 127.0.0.1
#     username: myself
#     password: secret
#     nonProxyHosts: localhost,192.168.0.*
#   socks:
#     port: 8080
#     host: 127.0.0.1
#     username: myself
#     password: secret
#     version: 5
